### ISSUE TITLE
crashes on startup over "FurnaceBurnEvent"

### ISSUE THREAD

**Issue by Risklessmcx** [itsdinkd/AQM3#141]
[16:37:53] [Netty Server IO #6/ERROR] [minecraft/ArgumentTypes]: Could not serialize chanceCubes.commands.RewardArgument@e96db99 (class chanceCubes.commands.RewardArgument) - will not be sent to client!
[16:37:53] [Netty Server IO #6/ERROR] [minecraft/ArgumentTypes]: Could not serialize chanceCubes.commands.RewardArgument@23843512 (class chanceCubes.commands.RewardArgument) - will not be sent to client!
[16:37:53] [Netty Server IO #6/ERROR] [minecraft/ArgumentTypes]: Could not serialize chanceCubes.commands.RewardInfoActionArgument@30bf3fbe (class chanceCubes.commands.RewardInfoActionArgument) - will not be sent to client!
[16:37:53] [Netty Server IO #6/ERROR] [minecraft/ArgumentTypes]: Could not serialize chanceCubes.commands.RewardArgument@4ad49c73 (class chanceCubes.commands.RewardArgument) - will not be sent to client!
[16:37:53] [Netty Server IO #6/ERROR] [minecraft/ArgumentTypes]: Could not serialize io.github.apace100.apoli.command.PowerSourceArgumentType@64c118fb (class io.github.apace100.apoli.command.PowerSourceArgumentType) - will not be sent to client!
[16:37:53] [Netty Server IO #6/ERROR] [minecraft/ArgumentTypes]: Could not serialize io.github.apace100.apoli.command.PowerSourceArgumentType@17315048 (class io.github.apace100.apoli.command.PowerSourceArgumentType) - will not be sent to client!
[16:37:53] [Netty Server IO #6/ERROR] [minecraft/ArgumentTypes]: Could not serialize io.github.apace100.apoli.command.PowerSourceArgumentType@6a715942 (class io.github.apace100.apoli.command.PowerSourceArgumentType) - will not be sent to client!
[16:37:53] [Netty Server IO #6/ERROR] [minecraft/ArgumentTypes]: Could not serialize chanceCubes.commands.RewardArgument@e96db99 (class chanceCubes.commands.RewardArgument) - will not be sent to client!
[16:37:53] [Netty Server IO #6/ERROR] [minecraft/ArgumentTypes]: Could not serialize chanceCubes.commands.RewardArgument@23843512 (class chanceCubes.commands.RewardArgument) - will not be sent to client!
[16:37:53] [Netty Server IO #6/ERROR] [minecraft/ArgumentTypes]: Could not serialize chanceCubes.commands.RewardInfoActionArgument@30bf3fbe (class chanceCubes.commands.RewardInfoActionArgument) - will not be sent to client!
[16:37:53] [Netty Server IO #6/ERROR] [minecraft/ArgumentTypes]: Could not serialize chanceCubes.commands.RewardArgument@4ad49c73 (class chanceCubes.commands.RewardArgument) - will not be sent to client!
[16:37:53] [Netty Server IO #6/ERROR] [minecraft/ArgumentTypes]: Could not serialize io.github.apace100.apoli.command.PowerSourceArgumentType@64c118fb (class io.github.apace100.apoli.command.PowerSourceArgumentType) - will not be sent to client!
[16:37:53] [Netty Server IO #6/ERROR] [minecraft/ArgumentTypes]: Could not serialize io.github.apace100.apoli.command.PowerSourceArgumentType@17315048 (class io.github.apace100.apoli.command.PowerSourceArgumentType) - will not be sent to client!
[16:37:53] [Netty Server IO #6/ERROR] [minecraft/ArgumentTypes]: Could not serialize io.github.apace100.apoli.command.PowerSourceArgumentType@6a715942 (class io.github.apace100.apoli.command.PowerSourceArgumentType) - will not be sent to client!
[16:38:04] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception

Caused by: java.lang.ClassNotFoundException: harmonised.pmmo.api.events.FurnaceBurnEvent
        at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:138) ~[securejarhandler-1.0.3.jar:?] {}
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?] {}
        at ironfurnaces.tileentity.furnaces.BlockIronFurnaceTileBase.handleSmeltedPMMO(BlockIronFurnaceTileBase.java:1622) ~[ironfurnaces-1.18.2-3.3.3.jar%23191!/:3.3.3] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:polymorph_integrations.mixins.json:ironfurnaces.AccessorBlockIronFurnaceTileBase,pl:mixin:APP:polymorph_integrations.mixins.json:ironfurnaces.MixinBlockIronFurnaceTileBase,pl:mixin:A}
        at ironfurnaces.tileentity.furnaces.BlockIronFurnaceTileBase.smeltItem(BlockIronFurnaceTileBase.java:1512) ~[ironfurnaces-1.18.2-3.3.3.jar%23191!/:3.3.3] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:polymorph_integrations.mixins.json:ironfurnaces.AccessorBlockIronFurnaceTileBase,pl:mixin:APP:polymorph_integrations.mixins.json:ironfurnaces.MixinBlockIronFurnaceTileBase,pl:mixin:A}
        at ironfurnaces.tileentity.furnaces.BlockIronFurnaceTileBase.smelt(BlockIronFurnaceTileBase.java:1460) ~[ironfurnaces-1.18.2-3.3.3.jar%23191!/:3.3.3] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:polymorph_integrations.mixins.json:ironfurnaces.AccessorBlockIronFurnaceTileBase,pl:mixin:APP:polymorph_integrations.mixins.json:ironfurnaces.MixinBlockIronFurnaceTileBase,pl:mixin:A}
        at ironfurnaces.tileentity.furnaces.BlockIronFurnaceTileBase.tick(BlockIronFurnaceTileBase.java:926) ~[ironfurnaces-1.18.2-3.3.3.jar%23191!/:3.3.3] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:APP:polymorph_integrations.mixins.json:ironfurnaces.AccessorBlockIronFurnaceTileBase,pl:mixin:APP:polymorph_integrations.mixins.json:ironfurnaces.MixinBlockIronFurnaceTileBase,pl:mixin:A}
        at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:673) ~[server-1.18.2-20220404.173914-srg.jar%23368!/:?] {re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B}
        at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:766) ~[server-1.18.2-20220404.173914-srg.jar%23368!/:?] {re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B}
        at net.minecraft.world.level.Level.m_46463_(Level.java:476) ~[server-1.18.2-20220404.173914-srg.jar%23368!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:kubejs-common.mixins.json:LevelMixin,pl:mixin:APP:strawgolem.forge.mixins.json:GrowthMixin,pl:mixin:APP:starlight.mixins.json:common.world.LevelMixin,pl:mixin:APP:lootr.mixins.json:MixinLevel,pl:mixin:A}
        at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:327) ~[server-1.18.2-20220404.173914-srg.jar%23368!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,xf:fml:forgeendertech:coremod,pl:mixin:APP:strawgolem.mixins.json:LoginMixin,pl:mixin:APP:botania_xplat.mixins.json:MixinServerLevel,pl:mixin:APP:starlight.mixins.json:common.world.ServerWorldMixin,pl:mixin:APP:byg.mixins.json:common.world.MixinServerLevel,pl:mixin:APP:flan.mixins.json:ServerWorldMixin,pl:mixin:APP:simplerpc.mixins.json:ServerWorldMixin,pl:mixin:APP:create.mixins.json:accessor.ServerLevelAccessor,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:902) ~[server-1.18.2-20220404.173914-srg.jar%23368!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:flytre_lib.mixins.json:base.MinecraftServerMixin,pl:mixin:APP:flytre_lib.mixins.json:config.MinecraftServerMixin,pl:mixin:APP:terrablender.mixins.json:MixinMinecraftServer,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:flan.mixins.json:MinecraftServerMixin,pl:mixin:A}

**Comment by tmvkrpxl0** [comment]
This is because Project MMO version is quite ancient. Most latest version for 1.18.2 is 1.18.2-5.1.3, but this modpack has 1.18.2-3.69.11 instead.

**Comment by PainXpress** [comment]
Encountered same issue, seems to involve specifically the iron furnace in pack at least in this instance (in smelting process). 
[crash-2023-02-07_21.58.15-server.txt](https://github.com/itsdinkd/AQM3/files/10681525/crash-2023-02-07_21.58.15-server.txt)

**Comment by Madonno** [comment]
> This is because Project MMO version is quite ancient. Most latest version for 1.18.2 is 1.18.2-5.1.3, but this modpack has 1.18.2-3.69.11 instead.

I had the same issue, but I just chalked it up to something wrong with iron furnaces disappointedly. I hadn't seen pmmo in my crash report until I read this. Is it something to do with the way PMMO calculates smelting XP?

**Comment by tmvkrpxl0** [comment]
> > This is because Project MMO version is quite ancient. Most latest version for 1.18.2 is 1.18.2-5.1.3, but this modpack has 1.18.2-3.69.11 instead.
> 
> I had the same issue, but I just chalked it up to something wrong with iron furnaces disappointedly. I hadn't seen pmmo in my crash report until I read this. Is it something to do with the way PMMO calculates smelting XP?

No, It calls event from recent version of PMMO. but it doesn't exist here

**Comment by Bukighost** [comment]
This is still an issue just happened to my server as well.

**Comment by itsdinkd** [comment]
was fixed along time ago
