### ISSUE TITLE
Server files not downloading

### ISSUE THREAD

**Issue by SamSprink** [itsdinkd/AQM3#16]
When trying to run first time setup, fails to download/install modloader

**Comment by SamSprink** [comment]
[00:07:38] [INFO] Attempting to download installer from https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.18.1-39.0.10/forge-1.18.1-39.0.10-installer.jar
[00:07:38] [ERROR] Problem while installing Loader from https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.18.1-39.0.10/forge-1.18.1-39.0.10-installer.jar

java.io.IOException: Expected a SETTINGS frame but was GOAWAY
        at okhttp3.internal.http2.Http2Reader.nextFrame(Http2Reader.kt:115)
        at okhttp3.internal.http2.Http2Reader.readConnectionPreface(Http2Reader.kt:73)
        at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:617)
        at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:609)
        at okhttp3.internal.concurrent.TaskQueue$execute$1.runOnce(TaskQueue.kt:98)
        at okhttp3.internal.concurrent.TaskRunner.runTask(TaskRunner.kt:116)
        at okhttp3.internal.concurrent.TaskRunner.access$runTask(TaskRunner.kt:42)
        at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:65)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
[00:07:38] [ERROR] Stopping the process as downloading the ModLoader failed

atm.bloodworkxgaming.serverstarter.DownloadLoaderException: Problem while installing Loader from https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.18.1-39.0.10/forge-1.18.1-39.0.10-installer.jar
        at atm.bloodworkxgaming.serverstarter.LoaderManager.installLoader(LoaderManager.kt:168)
        at atm.bloodworkxgaming.serverstarter.ServerStarter.startLoading(ServerStarter.kt:169)
        at atm.bloodworkxgaming.serverstarter.ServerStarterKt.main(ServerStarter.kt:204)
Caused by: java.io.IOException: Expected a SETTINGS frame but was GOAWAY
        at okhttp3.internal.http2.Http2Reader.nextFrame(Http2Reader.kt:115)
        at okhttp3.internal.http2.Http2Reader.readConnectionPreface(Http2Reader.kt:73)
        at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:617)
        at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:609)
        at okhttp3.internal.concurrent.TaskQueue$execute$1.runOnce(TaskQueue.kt:98)
        at okhttp3.internal.concurrent.TaskRunner.runTask(TaskRunner.kt:116)
        at okhttp3.internal.concurrent.TaskRunner.access$runTask(TaskRunner.kt:42)
        at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:65)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

**Comment by SamSprink** [comment]
fixed
