### ISSUE TITLE
Server Crash with Nether Portal Lootr Chest

### ISSUE THREAD

**Issue by FaynaStalwart** [itsdinkd/AQM3#30]
I'm hosting through Bisect and they suggested that I report an issue with something going on with Lootr. Every time I try to open this chest, the server crashes and this is it's report. If you can help out, that'd be wonderful! Thank you <3

[Server] ---- Minecraft Crash Report ----
[21.01 13:02:03] [Server] // This doesn't make any sense!
[21.01 13:02:03] [Server] Time1/21/22, 2:02 PM
[21.01 13:02:03] [Server] DescriptionWatching Server
[21.01 13:02:03] [Server] java.lang.ErrorServerHangWatchdog detected that a single server tick took 60.01 seconds (should be max 0.05)
[21.01 13:02:03] [Server] 	at terrablender.worldgen.TBClimate$RTree$SubTree.search(TBClimate.java:425) ~[TerraBlender-forge-1.18.1-1.1.0.54.jar%23291!:1.18.1-1.1.0.{re:classloading,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at terrablender.worldgen.TBClimate$RTree$SubTree.search(TBClimate.java:425) ~[TerraBlender-forge-1.18.1-1.1.0.54.jar%23291!:1.18.1-1.1.0.{re:classloading,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at terrablender.worldgen.TBClimate$RTree.search(TBClimate.java:364) ~[TerraBlender-forge-1.18.1-1.1.0.54.jar%23291!:1.18.1-1.1.0.{re:classloading,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at terrablender.worldgen.TBClimate$UniquenessRTree.search(TBClimate.java:177) ~[TerraBlender-forge-1.18.1-1.1.0.54.jar%23291!:1.18.1-1.1.0.{re:classloading,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at terrablender.worldgen.TBClimate$ParameterList.findValueIndex(TBClimate.java:97) ~[TerraBlender-forge-1.18.1-1.1.0.54.jar%23291!:1.18.1-1.1.0.{re:classloading,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at terrablender.worldgen.TBClimate$ParameterList.findValueIndex(TBClimate.java:93) ~[TerraBlender-forge-1.18.1-1.1.0.54.jar%23291!:1.18.1-1.1.0.{re:classloading,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at terrablender.worldgen.TBClimate$ParameterList.findValue(TBClimate.java:89) ~[TerraBlender-forge-1.18.1-1.1.0.54.jar%23291!:1.18.1-1.1.0.{re:classloading,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at terrablender.worldgen.TBMultiNoiseBiomeSource.getNoiseBiome(TBMultiNoiseBiomeSource.java:110) ~[TerraBlender-forge-1.18.1-1.1.0.54.jar%23291!:1.18.1-1.1.0.{re:classloading,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at terrablender.worldgen.TBMultiNoiseBiomeSource.m_183546_(TBMultiNoiseBiomeSource.java:94) ~[TerraBlender-forge-1.18.1-1.1.0.54.jar%23291!:1.18.1-1.1.0.{re:classloading,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at net.minecraft.world.level.chunk.ChunkGenerator.m_7158_(ChunkGenerator.java:180) ~[server-1.18.1-20211210.034407-srg.jar%23319!:?] {re:mixin,re:classloading,pl:mixin:APP:citadel.mixins.json:ChunkGeneratorMixin,pl:mixin:APP:repurposed_structures.mixins.json:world.ChunkGeneratorAccessor,pl:mixin:APP:supplementaries.mixins.json:accessors.ChunkGeneratorAccessor,pl:mixin:A,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at net.minecraft.server.level.ServerLevel.m_6159_(ServerLevel.java:236) ~[server-1.18.1-20211210.034407-srg.jar%23319!:?] {re:mixin,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,re:classloading,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:krypton.mixins.json:server.fastchunkentityaccess.ServerWorldMixin,pl:mixin:A,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at net.minecraft.world.level.LevelReader.m_7158_(LevelReader.java:54) ~[server-1.18.1-20211210.034407-srg.jar%23319!:?] {re:computing_frames,pl:epic_rei_lmao:A,re:mixin,re:classloading,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at net.minecraft.world.level.biome.BiomeManager.m_47881_(BiomeManager.java:78) ~[server-1.18.1-20211210.034407-srg.jar%23319!:?] {re:classloading,pl:accesstransformer:B,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at net.minecraft.world.level.LevelReader.m_46857_(LevelReader.java:35) ~[server-1.18.1-20211210.034407-srg.jar%23319!:?] {re:computing_frames,pl:epic_rei_lmao:A,re:mixin,re:classloading,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at net.minecraft.world.item.MapItem.m_42850_(MapItem.java:239) ~[server-1.18.1-20211210.034407-srg.jar%23319!:?] {re:mixin,re:classloading,pl:mixin:APP:selene.mixins.json:MapItemMixin,pl:mixin:A,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at net.minecraft.world.level.storage.loot.functions.ExplorationMapFunction.m_7372_(ExplorationMapFunction.java:75) ~[server-1.18.1-20211210.034407-srg.jar%23319!:?] {re:classloading,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at net.minecraft.world.level.storage.loot.functions.LootItemConditionalFunction.apply(LootItemConditionalFunction.java:31) ~[server-1.18.1-20211210.034407-srg.jar%23319!:?] {re:classloading,pl:epic_rei_lmao:A,re:mixin}
[21.01 13:02:03] [Server] 	at net.minecraft.world.level.storage.loot.functions.LootItemConditionalFunction.apply(LootItemConditionalFunction.java:20) ~[server-1.18.1-20211210.034407-srg.jar%23319!:?] {re:classloading,pl:epic_rei_lmao:A,re:mixin}
[21.01 13:02:03] [Server] 	at net.minecraft.world.level.storage.loot.functions.LootItemFunction.m_80728_(LootItemFunction.java:14) ~[server-1.18.1-20211210.034407-srg.jar%23319!:?] {re:classloading,pl:epic_rei_lmao:A,re:mixin}
[21.01 13:02:03] [Server] 	at net.minecraft.world.level.storage.loot.functions.LootItemFunction$$Lambda$32350/0x00000008041fd000.accept(Unknown Source) ~[?:?] {}
[21.01 13:02:03] [Server] 	at net.minecraft.world.level.storage.loot.entries.LootItem.m_6948_(LootItem.java:33) ~[server-1.18.1-20211210.034407-srg.jar%23319!:?] {re:classloading,pl:accesstransformer:B,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at net.minecraft.world.level.storage.loot.entries.LootPoolSingletonContainer$1.m_6941_(LootPoolSingletonContainer.java:59) ~[server-1.18.1-20211210.034407-srg.jar%23319!:?] {re:classloading,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at net.minecraft.world.level.storage.loot.LootPool.m_79058_(LootPool.java:80) ~[server-1.18.1-20211210.034407-srg.jar%23319!:?] {re:classloading,pl:accesstransformer:B,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at net.minecraft.world.level.storage.loot.LootPool.m_79053_(LootPool.java:95) ~[server-1.18.1-20211210.034407-srg.jar%23319!:?] {re:classloading,pl:accesstransformer:B,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at net.minecraft.world.level.storage.loot.LootTable.m_79131_(LootTable.java:71) ~[server-1.18.1-20211210.034407-srg.jar%23319!:?] {re:classloading,pl:epic_rei_lmao:A,re:mixin}
[21.01 13:02:03] [Server] 	at net.minecraft.world.level.storage.loot.entries.LootTableReference.m_6948_(LootTableReference.java:33) ~[server-1.18.1-20211210.034407-srg.jar%23319!:?] {re:classloading,pl:accesstransformer:B,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at net.minecraft.world.level.storage.loot.entries.LootPoolSingletonContainer$1.m_6941_(LootPoolSingletonContainer.java:59) ~[server-1.18.1-20211210.034407-srg.jar%23319!:?] {re:classloading,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at net.minecraft.world.level.storage.loot.LootPool.m_79058_(LootPool.java:73) ~[server-1.18.1-20211210.034407-srg.jar%23319!:?] {re:classloading,pl:accesstransformer:B,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at net.minecraft.world.level.storage.loot.LootPool.m_79053_(LootPool.java:95) ~[server-1.18.1-20211210.034407-srg.jar%23319!:?] {re:classloading,pl:accesstransformer:B,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at net.minecraft.world.level.storage.loot.LootTable.m_79131_(LootTable.java:71) ~[server-1.18.1-20211210.034407-srg.jar%23319!:?] {re:classloading,pl:epic_rei_lmao:A,re:mixin}
[21.01 13:02:03] [Server] 	at net.minecraft.world.level.storage.loot.LootTable.m_79148_(LootTable.java:83) ~[server-1.18.1-20211210.034407-srg.jar%23319!:?] {re:classloading,pl:epic_rei_lmao:A,re:mixin}
[21.01 13:02:03] [Server] 	at net.minecraft.world.level.storage.loot.LootTable.m_79129_(LootTable.java:88) ~[server-1.18.1-20211210.034407-srg.jar%23319!:?] {re:classloading,pl:epic_rei_lmao:A,re:mixin}
[21.01 13:02:03] [Server] 	at net.minecraft.world.level.storage.loot.LootTable.m_79123_(LootTable.java:109) ~[server-1.18.1-20211210.034407-srg.jar%23319!:?] {re:classloading,pl:epic_rei_lmao:A,re:mixin}
[21.01 13:02:03] [Server] 	at noobanidus.mods.lootr.block.entities.LootrChestBlockEntity.unpackLootTable(LootrChestBlockEntity.java:275) ~[lootr-1.18-0.1.13.40.jar%23193!:0.1.13.{re:mixin,re:classloading,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at noobanidus.mods.lootr.util.ChestUtil$$Lambda$32785/0x0000000804262200.fillWithLoot(Unknown Source) ~[?:?] {}
[21.01 13:02:03] [Server] 	at noobanidus.mods.lootr.data.ChestData.createInventory(ChestData.java:187) ~[lootr-1.18-0.1.13.40.jar%23193!:0.1.13.{re:classloading,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at noobanidus.mods.lootr.data.DataStorage.getInventory(DataStorage.java:164) ~[lootr-1.18-0.1.13.40.jar%23193!:0.1.13.{re:classloading,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at noobanidus.mods.lootr.util.ChestUtil.handleLootChest(ChestUtil.java:127) ~[lootr-1.18-0.1.13.40.jar%23193!:0.1.13.{re:classloading,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at noobanidus.mods.lootr.block.LootrChestBlock.m_6227_(LootrChestBlock.java:48) ~[lootr-1.18-0.1.13.40.jar%23193!:0.1.13.{re:classloading,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60664_(BlockBehaviour.java:695) ~[server-1.18.1-20211210.034407-srg.jar%23319!:?] {re:mixin,pl:accesstransformer:B,xf:fml:libx:random_tick_block,re:classloading,pl:accesstransformer:B,xf:fml:libx:random_tick_block,pl:mixin:APP:ferritecore.blockstatecache.mixin.json:BlockStateBaseMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.AbstractBlockStateMixin,pl:mixin:APP:kubejs-common.mixins.json:BlockStateBaseMixin,pl:mixin:APP:slashblade.mixins.json:MixinBlockBehaviour,pl:mixin:APP:valhelsia_structures.mixins.json:BlockStateBaseMixin,pl:mixin:A,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at net.minecraft.server.level.ServerPlayerGameMode.m_7179_(ServerPlayerGameMode.java:335) ~[server-1.18.1-20211210.034407-srg.jar%23319!:?] {re:mixin,xf:fml:libx:interact,re:computing_frames,xf:fml:libx:interact,pl:epic_rei_lmao:A,re:classloading,xf:fml:libx:interact,pl:mixin:APP:kubejs-common.mixins.json:ServerPlayerGameModeMixin,pl:mixin:A,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6371_(ServerGamePacketListenerImpl.java:975) ~[server-1.18.1-20211210.034407-srg.jar%23319!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:30) ~[server-1.18.1-20211210.034407-srg.jar%23319!:?] {re:classloading,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:8) ~[server-1.18.1-20211210.034407-srg.jar%23319!:?] {re:classloading,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:21) ~[server-1.18.1-20211210.034407-srg.jar%23319!:?] {re:classloading,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at net.minecraft.network.protocol.PacketUtils$$Lambda$32125/0x00000008041c64b0.run(Unknown Source) ~[?:?] {}
[21.01 13:02:03] [Server] 	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.18.1-20211210.034407-srg.jar%23319!:?] {re:classloading,pl:epic_rei_lmao:A,re:mixin}
[21.01 13:02:03] [Server] 	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151) ~[server-1.18.1-20211210.034407-srg.jar%23319!:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,pl:epic_rei_lmao:A,re:classloading,pl:accesstransformer:B,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.18.1-20211210.034407-srg.jar%23319!:?] {re:mixin,re:computing_frames,pl:epic_rei_lmao:A,re:classloading,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:765) ~[server-1.18.1-20211210.034407-srg.jar%23319!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[server-1.18.1-20211210.034407-srg.jar%23319!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:125) ~[server-1.18.1-20211210.034407-srg.jar%23319!:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,pl:epic_rei_lmao:A,re:classloading,pl:accesstransformer:B,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:748) ~[server-1.18.1-20211210.034407-srg.jar%23319!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:742) ~[server-1.18.1-20211210.034407-srg.jar%23319!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:134) ~[server-1.18.1-20211210.034407-srg.jar%23319!:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,pl:epic_rei_lmao:A,re:classloading,pl:accesstransformer:B,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:728) ~[server-1.18.1-20211210.034407-srg.jar%23319!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:672) ~[server-1.18.1-20211210.034407-srg.jar%23319!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%23319!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftServerAccessor,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:A,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at net.minecraft.server.MinecraftServer$$Lambda$28615/0x0000000803d99900.run(Unknown Source) ~[?:?] {}
[21.01 13:02:03] [Server] 	at java.lang.Thread.run(Thread.java:833) [?:?] {}
[21.01 13:02:03] [Server] A detailed walkthrough of the error, its code path and all known details is as follows:
[21.01 13:02:03] [Server] ---------------------------------------------------------------------------------------
[21.01 13:02:03] [Server] -- Head --
[21.01 13:02:03] [Server] ThreadServer Watchdog
[21.01 13:02:03] [Server] Stacktrace:
[21.01 13:02:03] [Server] 	at terrablender.worldgen.TBClimate$RTree$SubTree.search(TBClimate.java:425) ~[TerraBlender-forge-1.18.1-1.1.0.54.jar%23291!:1.18.1-1.1.0.{re:classloading,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at terrablender.worldgen.TBClimate$RTree$SubTree.search(TBClimate.java:425) ~[TerraBlender-forge-1.18.1-1.1.0.54.jar%23291!:1.18.1-1.1.0.{re:classloading,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at terrablender.worldgen.TBClimate$RTree.search(TBClimate.java:364) ~[TerraBlender-forge-1.18.1-1.1.0.54.jar%23291!:1.18.1-1.1.0.{re:classloading,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at terrablender.worldgen.TBClimate$UniquenessRTree.search(TBClimate.java:177) ~[TerraBlender-forge-1.18.1-1.1.0.54.jar%23291!:1.18.1-1.1.0.{re:classloading,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at terrablender.worldgen.TBClimate$ParameterList.findValueIndex(TBClimate.java:97) ~[TerraBlender-forge-1.18.1-1.1.0.54.jar%23291!:1.18.1-1.1.0.{re:classloading,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at terrablender.worldgen.TBClimate$ParameterList.findValueIndex(TBClimate.java:93) ~[TerraBlender-forge-1.18.1-1.1.0.54.jar%23291!:1.18.1-1.1.0.{re:classloading,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at terrablender.worldgen.TBClimate$ParameterList.findValue(TBClimate.java:89) ~[TerraBlender-forge-1.18.1-1.1.0.54.jar%23291!:1.18.1-1.1.0.{re:classloading,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at terrablender.worldgen.TBMultiNoiseBiomeSource.getNoiseBiome(TBMultiNoiseBiomeSource.java:110) ~[TerraBlender-forge-1.18.1-1.1.0.54.jar%23291!:1.18.1-1.1.0.{re:classloading,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at terrablender.worldgen.TBMultiNoiseBiomeSource.m_183546_(TBMultiNoiseBiomeSource.java:94) ~[TerraBlender-forge-1.18.1-1.1.0.54.jar%23291!:1.18.1-1.1.0.{re:classloading,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at net.minecraft.world.level.chunk.ChunkGenerator.m_7158_(ChunkGenerator.java:180) ~[server-1.18.1-20211210.034407-srg.jar%23319!:?] {re:mixin,re:classloading,pl:mixin:APP:citadel.mixins.json:ChunkGeneratorMixin,pl:mixin:APP:repurposed_structures.mixins.json:world.ChunkGeneratorAccessor,pl:mixin:APP:supplementaries.mixins.json:accessors.ChunkGeneratorAccessor,pl:mixin:A,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at net.minecraft.server.level.ServerLevel.m_6159_(ServerLevel.java:236) ~[server-1.18.1-20211210.034407-srg.jar%23319!:?] {re:mixin,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,re:classloading,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,pl:mixin:APP:immersiveengineering.mixins.json:coremods.ServerWorldMixin,pl:mixin:APP:krypton.mixins.json:server.fastchunkentityaccess.ServerWorldMixin,pl:mixin:A,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at net.minecraft.world.level.LevelReader.m_7158_(LevelReader.java:54) ~[server-1.18.1-20211210.034407-srg.jar%23319!:?] {re:computing_frames,pl:epic_rei_lmao:A,re:mixin,re:classloading,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at net.minecraft.world.level.biome.BiomeManager.m_47881_(BiomeManager.java:78) ~[server-1.18.1-20211210.034407-srg.jar%23319!:?] {re:classloading,pl:accesstransformer:B,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at net.minecraft.world.level.LevelReader.m_46857_(LevelReader.java:35) ~[server-1.18.1-20211210.034407-srg.jar%23319!:?] {re:computing_frames,pl:epic_rei_lmao:A,re:mixin,re:classloading,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at net.minecraft.world.item.MapItem.m_42850_(MapItem.java:239) ~[server-1.18.1-20211210.034407-srg.jar%23319!:?] {re:mixin,re:classloading,pl:mixin:APP:selene.mixins.json:MapItemMixin,pl:mixin:A,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at net.minecraft.world.level.storage.loot.functions.ExplorationMapFunction.m_7372_(ExplorationMapFunction.java:75) ~[server-1.18.1-20211210.034407-srg.jar%23319!:?] {re:classloading,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at net.minecraft.world.level.storage.loot.functions.LootItemConditionalFunction.apply(LootItemConditionalFunction.java:31) ~[server-1.18.1-20211210.034407-srg.jar%23319!:?] {re:classloading,pl:epic_rei_lmao:A,re:mixin}
[21.01 13:02:03] [Server] 	at net.minecraft.world.level.storage.loot.functions.LootItemConditionalFunction.apply(LootItemConditionalFunction.java:20) ~[server-1.18.1-20211210.034407-srg.jar%23319!:?] {re:classloading,pl:epic_rei_lmao:A,re:mixin}
[21.01 13:02:03] [Server] 	at net.minecraft.world.level.storage.loot.functions.LootItemFunction.m_80728_(LootItemFunction.java:14) ~[server-1.18.1-20211210.034407-srg.jar%23319!:?] {re:classloading,pl:epic_rei_lmao:A,re:mixin}
[21.01 13:02:03] [Server] 	at net.minecraft.world.level.storage.loot.functions.LootItemFunction$$Lambda$32350/0x00000008041fd000.accept(Unknown Source) ~[?:?] {}
[21.01 13:02:03] [Server] 	at net.minecraft.world.level.storage.loot.entries.LootItem.m_6948_(LootItem.java:33) ~[server-1.18.1-20211210.034407-srg.jar%23319!:?] {re:classloading,pl:accesstransformer:B,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at net.minecraft.world.level.storage.loot.entries.LootPoolSingletonContainer$1.m_6941_(LootPoolSingletonContainer.java:59) ~[server-1.18.1-20211210.034407-srg.jar%23319!:?] {re:classloading,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at net.minecraft.world.level.storage.loot.LootPool.m_79058_(LootPool.java:80) ~[server-1.18.1-20211210.034407-srg.jar%23319!:?] {re:classloading,pl:accesstransformer:B,pl:epic_rei_lmao:A}
[21.01 13:02:03] [Server] 	at net.minecraft.world.level.storage.loot.LootPool.m_79053_(LootPool.java:95) ~[server-1.18.1-20211210.034407-srg.jar%23319!:?] {re:classloading,pl:accesstransformer:B,pl:epic_rei_lmao:A}
[21.01 13:02:14] [Multicraft] Server shut down (running)
[21.01 13:02:14] [Multicraft] Restarting crashed server in 2.0 seconds
[21.01 13:02:14] [Multicraft] Looks like a crash, check the server console. Return value: 1
[21.01 13:02:14] [Multicraft] Server stopped

**Comment by itsdinkd** [comment]
Should be fixed in later versions. please let me know if that isn't the case, especially on 1.4
