### ISSUE TITLE
[ERROR] Server installation

### ISSUE THREAD

**Issue by xMSDOSx** [itsdinkd/AQM3#59]
**Modpack Version**
Server AQM3 v1.7
**Minecraft Version**
1.18.1
**Describe the bug**
Error when installing the server.

**To Reproduce**
1. Run "startserver.bat"

**Crash log or latest.log.log**
```
[18:16:48] [INFO] Attempting to download installer from https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.18.1-39.0.79/forge-1.18.1-39.0.79-installer.jar
[18:16:49] [ERROR] Problem while installing Loader from https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.18.1-39.0.79/forge-1.18.1-39.0.79-installer.jar

java.io.IOException: Expected a SETTINGS frame but was GOAWAY
        at okhttp3.internal.http2.Http2Reader.nextFrame(Http2Reader.kt:115)
        at okhttp3.internal.http2.Http2Reader.readConnectionPreface(Http2Reader.kt:73)
        at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:617)
        at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:609)
        at okhttp3.internal.concurrent.TaskQueue$execute$1.runOnce(TaskQueue.kt:98)
        at okhttp3.internal.concurrent.TaskRunner.runTask(TaskRunner.kt:116)
        at okhttp3.internal.concurrent.TaskRunner.access$runTask(TaskRunner.kt:42)
        at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:65)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[18:16:49] [ERROR] Stopping the process as downloading the ModLoader failed

atm.bloodworkxgaming.serverstarter.DownloadLoaderException: Problem while installing Loader from https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.18.1-39.0.79/forge-1.18.1-39.0.79-installer.jar
        at atm.bloodworkxgaming.serverstarter.LoaderManager.installLoader(LoaderManager.kt:168)
        at atm.bloodworkxgaming.serverstarter.ServerStarter.startLoading(ServerStarter.kt:169)
        at atm.bloodworkxgaming.serverstarter.ServerStarterKt.main(ServerStarter.kt:204)
Caused by: java.io.IOException: Expected a SETTINGS frame but was GOAWAY
        at okhttp3.internal.http2.Http2Reader.nextFrame(Http2Reader.kt:115)
        at okhttp3.internal.http2.Http2Reader.readConnectionPreface(Http2Reader.kt:73)
        at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:617)
        at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:609)
        at okhttp3.internal.concurrent.TaskQueue$execute$1.runOnce(TaskQueue.kt:98)
        at okhttp3.internal.concurrent.TaskRunner.runTask(TaskRunner.kt:116)
        at okhttp3.internal.concurrent.TaskRunner.access$runTask(TaskRunner.kt:42)
        at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:65)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by xMSDOSx** [comment]
Sorry. Installing Java 17 solved the problem.
